In [1]:
import pandas as pd
import numpy as np
from pprint import pprint

In [6]:
# first = pd.read_csv("hai/HAI-Check/outputs/0318_pyojeol_full/new_pyojeol_full_20240312105126_5어절.csv",encoding='cp949')
# second = pd.read_csv("hai/HAI-Check/outputs/0318_pyojeol_full/new_pyojeol_full_20|240317231555_5어절.csv",encoding='cp949')
# third = pd.read_csv("hai/HAI-Check/outputs/0318_pyojeol_full/new_pyojeol_full_20240318151639_5어절.csv",encoding='cp949')
# # third = pd.read_csv("hai/HAI-Check/outputs/0318_pyojeol_full/철도.csv",encoding='cp949')
# third_1 = pd.read_csv("hai/HAI-Check/outputs/0318_pyojeol_full/new_pyojeol_full_20240320132255_5어절.csv",encoding='cp949')
# loc_han = pd.read_csv("hai/HAI-Check/outputs/한수원/로컬한수원2000.csv",encoding='cp949')
# ser_han = pd.read_csv("hai/HAI-Check/outputs/한수원/원격한수원2000.csv",encoding='cp949')
# loc_choel = pd.read_csv("hai/HAI-Check/outputs/철도/로컬철도2500.csv",encoding='cp949')
# ser_choel = pd.read_csv("hai/HAI-Check/outputs/철도/원격철도2500.csv",encoding='cp949')

com_choel_short = pd.read_csv("hai/HAI-Check/outputs/철도2500/combinations1000_short.csv",encoding='cp949')
per_choel_short = pd.read_csv("hai/HAI-Check/outputs/철도2500/permutations1000_short.csv",encoding='cp949')

com_choel_long = pd.read_csv("hai/HAI-Check/outputs/철도2500/combinations1000_long.csv",encoding='cp949')
per_choel_long = pd.read_csv("hai/HAI-Check/outputs/철도2500/permutations1000_long.csv",encoding='cp949')

In [30]:
(com_choel_short != per_choel_short).sum().sum()



632

In [33]:
com_choel_short[com_choel_short.loc[:, 'tot_rates(%)'] != per_choel_short.loc[:, 'tot_rates(%)']]['수험번호'].values

array([127, 219, 248, 262, 274, 296, 306, 334, 399, 438, 476, 480, 502,
       514, 515, 516, 521, 522, 538, 566, 594, 606, 612, 617, 623, 630,
       636, 640, 654, 659, 661, 666, 669, 674, 681, 686, 687, 692, 693,
       696, 701, 702, 705, 735, 740, 753, 755, 761, 765, 768, 774, 778,
       786, 787, 790, 799, 801, 818, 819, 825, 830, 844, 847, 849, 855,
       856, 859, 866, 867, 894, 904, 912, 916, 926, 932, 933, 934, 944,
       956, 961, 962, 972, 980, 986, 988, 993, 995, 998])

In [45]:
print(com_choel_short[com_choel_short['검출1'] != per_choel_short['검출1']]['수험번호'].values)
print(com_choel_short[com_choel_short['검출2'] != per_choel_short['검출2']]['수험번호'].values)
print(com_choel_short[com_choel_short['검출3'] != per_choel_short['검출3']]['수험번호'].values)
print(com_choel_short[com_choel_short['검출4'] != per_choel_short['검출4']]['수험번호'].values)

[ 33  44  51  61  93  96 113 127 138 142 156 192 207 219 221 224 231 237
 261 262 282 301 302 320 349 357 385 398 403 415 416 433 436 442 443 450
 477 480 486 493 496 497 502 506 514 516 521 526 538 541 566 573 611 612
 615 617 619 621 623 625 632 636 639 640 664 666 667 687 694 723 734 753
 755 761 768 774 784 790 819 855 856 858 859 867 877 904 906 912 916 922
 926 933 934 955 961 980 984 986 993 995 998]
[ 15  23  59  62  65  81  84  90 123 133 148 152 164 171 174 200 209 226
 241 243 254 259 266 274 306 323 324 326 356 364 365 374 378 401 421 444
 445 459 476 499 515 521 570 594 602 606 609 611 622 624 637 648 658 661
 669 681 687 693 696 701 702 705 723 735 736 744 745 748 765 790 815 816
 819 823 825 849 856 909 933 938 962 963 966 972 980 981 985 993 995]
[ 68  76  86  93 209 275 317 346 349 411 476 516 523 585 593 721 740 786
 795 801 809 818 844 854 862 866 894 912 924 966 993]
[  2   9  15  18  23  32  34  39  46  48  60  61  64  84  87 101 115 135
 140 143 161 171 187 188 22

In [46]:
idx = 44
print(com_choel_short.loc[com_choel_short['수험번호'] == idx, '검출1'].values)
print()
print(per_choel_short.loc[per_choel_short['수험번호'] == idx, '검출1'].values)

['{"4": {"user_ind": "760", "doc_ind": 2, "sent_ind": 6, "common_sent": "국민 모두를 위한 보편적 대중교통 서비스", "common_eojeol_cnt": 6, "short_common_sent": [], "short_common_eojeol_cnt": []}, "0": {"user_ind": "273", "doc_ind": 0, "sent_ind": 0, "common_sent": "가장 잘할 수 있는 곳이라고 생각하기 때문입니다.", "common_eojeol_cnt": 7, "short_common_sent": [], "short_common_eojeol_cnt": []}, "3": {"user_ind": "864", "doc_ind": 0, "sent_ind": 1, "common_sent": "한국철도공사는 전국 방방곡곡 사람과 물자를 실어 나르고 지역과 지역을", "common_eojeol_cnt": 9, "short_common_sent": [], "short_common_eojeol_cnt": []}}']

['{"0": {"user_ind": "273", "doc_ind": 0, "sent_ind": 0, "common_sent": "가장 잘할 수 있는 곳이라고 생각하기 때문입니다.", "common_eojeol_cnt": 7, "short_common_sent": [], "short_common_eojeol_cnt": []}, "4": {"user_ind": "744", "doc_ind": 3, "sent_ind": 1, "common_sent": "국민 모두를 위한 보편적 대중교통 서비스", "common_eojeol_cnt": 6, "short_common_sent": [], "short_common_eojeol_cnt": []}, "3": {"user_ind": "864", "doc_ind": 0, "sent_ind": 1, "common_sent": "한국철도공사는 전국 방방곡곡

In [78]:
long_index = com_choel_long[com_choel_long['검출정보_1'] != '0']['검출정보_1'].index
short_index = com_choel_short[com_choel_short['검출1'] != '0']['검출1'].index

for i in long_index:
    if i not in short_index:
        print(i)
        print(com_choel_long.loc[i, '수험번호'])
        print()

435
480

674
753

834
926

903
998



In [60]:
import json
for i in com_choel_long[com_choel_long['검출정보_1'] != '0']['검출정보_1']:
    i = json.loads(i)
    # print(json.loads(i).keys())
    for k, v in i.items():
        print(k, v)
    print()
        # print(json.loads(i).keys())

1 {'user_ind': 44, 'doc_ind': 0, 'sent_ind': 5, 'common_sent': '철도차량 개량 및 유지보수 업무에', 'common_eojeol_cnt': 5}

2 {'user_ind': 185, 'doc_ind': 0, 'sent_ind': 0, 'common_sent': '편리하게 이용할 수 있는 철도', 'common_eojeol_cnt': 5}

0 {'user_ind': 135, 'doc_ind': 0, 'sent_ind': 0, 'common_sent': '한국 철도에 지원한 동기는 제가', 'common_eojeol_cnt': 5}

1 {'user_ind': 437, 'doc_ind': 0, 'sent_ind': 0, 'common_sent': '지원한 동기는 제가 지닌 장점을 가장 발휘를 잘 할 수 있는 곳이라고 생각하기 때문입니다.', 'common_eojeol_cnt': 14}
2 {'user_ind': 569, 'doc_ind': 0, 'sent_ind': 2, 'common_sent': '한발 앞서 행동하여 만족도를 높이는 데 활용하곤', 'common_eojeol_cnt': 7}

0 {'user_ind': 769, 'doc_ind': 0, 'sent_ind': 1, 'common_sent': '국민 모두를 위한 보편적 대중교통', 'common_eojeol_cnt': 5}

0 {'user_ind': 570, 'doc_ind': 0, 'sent_ind': 2, 'common_sent': '제 능력을 발휘할 수 있는', 'common_eojeol_cnt': 5}

7 {'user_ind': 518, 'doc_ind': 0, 'sent_ind': 4, 'common_sent': '수행할 수 있도록 노력할 것입니다.', 'common_eojeol_cnt': 5}

2 {'user_ind': 468, 'doc_ind': 0, 'sent_ind': 7, 'common_sent': '바탕으로 입사 후 10년 

In [83]:
(com_choel_long != per_choel_long).sum().sum()

963

In [84]:
com_choel_long[com_choel_long.loc[:, 'tot_rates(%)'] != per_choel_long.loc[:, 'tot_rates(%)']]['수험번호'].values

array([ 15,  18,  19,  23,  39,  44,  52,  61,  70,  72,  93, 117, 126,
       127, 141, 143, 149, 151, 162, 167, 174, 175, 188, 192, 200, 203,
       207, 219, 230, 235, 248, 250, 254, 259, 261, 273, 274, 275, 290,
       296, 297, 302, 306, 316, 325, 334, 351, 356, 364, 365, 374, 376,
       379, 382, 399, 401, 431, 433, 436, 438, 444, 457, 480, 482, 496,
       497, 499, 502, 506, 515, 520, 521, 522, 526, 538, 556, 561, 566,
       585, 587, 597, 606, 612, 617, 619, 621, 623, 630, 636, 637, 640,
       648, 654, 659, 666, 674, 681, 691, 692, 693, 701, 722, 734, 735,
       740, 745, 755, 761, 774, 778, 784, 786, 787, 790, 794, 795, 799,
       801, 815, 818, 819, 821, 824, 830, 839, 840, 844, 856, 859, 866,
       867, 882, 892, 894, 901, 904, 906, 909, 912, 916, 926, 932, 933,
       934, 935, 956, 961, 962, 963, 966, 971, 972, 976, 980, 985, 986,
       993, 995, 999])

---

In [55]:
num = 12370
print(third.loc[num,"수험번호"], third.loc[num,"검출2"])
print(third_1.loc[num,"수험번호"], third_1.loc[num,"검출2"])

13062 {"7": {"user_ind": "13689", "doc_ind": 1, "sent_ind": 9, "common_sent": "공모전을 성공적으로 마무리할 수 있었습니다.", "common_eojeol_cnt": 5, "short_common_sent": [], "short_common_eojeol_cnt": []}}
13062 {"4": {"user_ind": "13741", "doc_ind": 2, "sent_ind": 2, "common_sent": "참여할 수 있는 환경을 만들기 위해", "common_eojeol_cnt": 6, "short_common_sent": [], "short_common_eojeol_cnt": []}, "7": {"user_ind": "13689", "doc_ind": 1, "sent_ind": 9, "common_sent": "공모전을 성공적으로 마무리할 수 있었습니다.", "common_eojeol_cnt": 5, "short_common_sent": [], "short_common_eojeol_cnt": []}}


In [11]:
first_result = first.iloc[:,-4:]
first_Qrates = first.iloc[:, 10:-4]
first_doc = first.iloc[:,3:7]
second_result = second.iloc[:,-4:]
second_Qrates = second.iloc[:, 10:-4]
second_doc = second.iloc[:,3:7]
third_result = third.iloc[:,-4:]
third_Qrates = third.iloc[:, 10:-4]
third_doc = third.iloc[:,3:7]
third_1_result = third_1.iloc[:,-4:]
third_1_Qrates = third_1.iloc[:, 10:-4]
third_1_doc = third_1.iloc[:,3:7]

idx = first['수험번호'].values

first_result.index = idx
first_Qrates.index = idx
first_doc.index = idx
second_result.index = idx
second_Qrates.index = idx
second_doc.index = idx
third_result.index = idx
third_Qrates.index = idx
third_doc.index = idx
third_1_result.index = idx
third_1_Qrates.index = idx
third_1_doc.index = idx

In [13]:
display(first_Qrates.sum())
display(second_Qrates.sum())
display(third_Qrates.sum())
display(third_1_Qrates.sum())

Q1_rates(%)    74929.07
Q2_rates(%)    43115.95
Q3_rates(%)    34783.55
Q4_rates(%)    61101.17
dtype: float64

Q1_rates(%)    74738.48
Q2_rates(%)    42946.22
Q3_rates(%)    34633.94
Q4_rates(%)    60967.37
dtype: float64

Q1_rates(%)    75236.40
Q2_rates(%)    42980.10
Q3_rates(%)    34747.58
Q4_rates(%)    61103.00
dtype: float64

Q1_rates(%)    75435.01
Q2_rates(%)    43146.91
Q3_rates(%)    34918.46
Q4_rates(%)    61282.14
dtype: float64

In [114]:
third_Qrates.loc[27,:]

Q1_rates(%)    5.32
Q2_rates(%)    9.65
Q3_rates(%)    4.85
Q4_rates(%)    8.40
Name: 27, dtype: float64

In [113]:
third_Qrates[first_Qrates > third_Qrates].dropna(how='all')

Q1_rates(%)  Q2_rates(%)  Q3_rates(%)  Q4_rates(%)
27             NaN         9.65          NaN          NaN
143            NaN          NaN          NaN        29.06
200          47.41          NaN          NaN          NaN
275            NaN          NaN          NaN        16.22
304            NaN          NaN          0.0          NaN
...            ...          ...          ...          ...
15719         8.24          NaN          NaN          NaN
15733         0.00          NaN          NaN          NaN
15766          NaN          NaN          NaN        13.53
15771         0.00          NaN          NaN          NaN
15779          NaN          NaN          NaN        19.71

[250 rows x 4 columns]

In [104]:
display(first_Qrates.loc[445,:])
display(second_Qrates.loc[445,:])

Q1_rates(%)    0.00
Q2_rates(%)    4.95
Q3_rates(%)    0.00
Q4_rates(%)    4.58
Name: 445, dtype: float64

Q1_rates(%)    0.00
Q2_rates(%)    4.95
Q3_rates(%)    0.00
Q4_rates(%)    3.82
Name: 445, dtype: float64

In [105]:
# print(first_doc.loc[27,"자기소개서2"].replace(". ", "\n"))
# print()
# print(first_doc.loc[3747,"자기소개서2"].replace(". ", "\n"))
# print()
# print(first_doc.loc[7066,"자기소개서3"].replace(". ", "\n"))
print("-"*100)
pprint(first_result.loc[445,"검출4"])
print("-"*100)
pprint(second_result.loc[445,"검출4"])

----------------------------------------------------------------------------------------------------
('{"1": {"user_ind": "1402", "doc_ind": 1, "sent_ind": 2, "common_sent": "통해 '
 '업무 효율을 높인 경험이 있습니다.", "common_eojeol_cnt": 6, "short_common_sent": [], '
 '"short_common_eojeol_cnt": []}}')
----------------------------------------------------------------------------------------------------
('{"1": {"user_ind": "10035", "doc_ind": 2, "sent_ind": 1, "common_sent": "업무 '
 '효율을 높인 경험이 있습니다.", "common_eojeol_cnt": 5, "short_common_sent": [], '
 '"short_common_eojeol_cnt": []}}')


In [14]:
(third_1_Qrates > 100).sum()

Q1_rates(%)    0
Q2_rates(%)    0
Q3_rates(%)    0
Q4_rates(%)    0
dtype: int64

---

In [7]:
com_choel_long = pd.read_csv("hai/HAI-Check/outputs/철도2500/combinations1000_long.csv",encoding='cp949')
per_choel_long = pd.read_csv("hai/HAI-Check/outputs/철도2500/permutations1000_long.csv",encoding='cp949')

In [10]:
(com_choel_long['tot_rates(%)'] != per_choel_long['tot_rates(%)']).sum()

159

In [11]:
com_choel_long[com_choel_long.loc[:, 'tot_rates(%)'] != per_choel_long.loc[:, 'tot_rates(%)']]['수험번호'].values

array([ 15,  18,  19,  23,  39,  44,  52,  61,  70,  72,  93, 117, 126,
       127, 141, 143, 149, 151, 162, 167, 174, 175, 188, 192, 200, 203,
       207, 219, 230, 235, 248, 250, 254, 259, 261, 273, 274, 275, 290,
       296, 297, 302, 306, 316, 325, 334, 351, 356, 364, 365, 374, 376,
       379, 382, 399, 401, 431, 433, 436, 438, 444, 457, 480, 482, 496,
       497, 499, 502, 506, 515, 520, 521, 522, 526, 538, 556, 561, 566,
       585, 587, 597, 606, 612, 617, 619, 621, 623, 630, 636, 637, 640,
       648, 654, 659, 666, 674, 681, 691, 692, 693, 701, 722, 734, 735,
       740, 745, 755, 761, 774, 778, 784, 786, 787, 790, 794, 795, 799,
       801, 815, 818, 819, 821, 824, 830, 839, 840, 844, 856, 859, 866,
       867, 882, 892, 894, 901, 904, 906, 909, 912, 916, 926, 932, 933,
       934, 935, 956, 961, 962, 963, 966, 971, 972, 976, 980, 985, 986,
       993, 995, 999])

---

In [12]:
per_choel_remote = pd.read_csv("hai/HAI-Check/outputs/철도2500/원격99_1000명.csv",encoding='cp949')

In [18]:
(per_choel_remote['tot_rates(%)'] != per_choel_short['tot_rates(%)']).sum()

0

In [19]:
per_choel_remote[per_choel_remote.loc[:, 'tot_rates(%)'] != per_choel_short.loc[:, 'tot_rates(%)']]['수험번호'].values

array([], dtype=int64)

---

In [21]:
from itertools import combinations, permutations
a = [(49, 0, 8), (58, 1, 4), (66, 0, 1), (104, 1, 5), (136, 0, 4), (139, 0, 3), (139, 1, 0), (139, 2, 4), (143, 1, 4), (144, 2, 5), (151, 1, 4), (165, 0, 0), (172, 0, 4), (189, 1, 8)]
a

[(49, 0, 8),
 (58, 1, 4),
 (66, 0, 1),
 (104, 1, 5),
 (136, 0, 4),
 (139, 0, 3),
 (139, 1, 0),
 (139, 2, 4),
 (143, 1, 4),
 (144, 2, 5),
 (151, 1, 4),
 (165, 0, 0),
 (172, 0, 4),
 (189, 1, 8)]

In [29]:
for idx, (p1, p2) in enumerate(combinations(a, 2)):
    print(p1, p2)
print(idx)

(49, 0, 8) (58, 1, 4)
(49, 0, 8) (66, 0, 1)
(49, 0, 8) (104, 1, 5)
(49, 0, 8) (136, 0, 4)
(49, 0, 8) (139, 0, 3)
(49, 0, 8) (139, 1, 0)
(49, 0, 8) (139, 2, 4)
(49, 0, 8) (143, 1, 4)
(49, 0, 8) (144, 2, 5)
(49, 0, 8) (151, 1, 4)
(49, 0, 8) (165, 0, 0)
(49, 0, 8) (172, 0, 4)
(49, 0, 8) (189, 1, 8)
(58, 1, 4) (66, 0, 1)
(58, 1, 4) (104, 1, 5)
(58, 1, 4) (136, 0, 4)
(58, 1, 4) (139, 0, 3)
(58, 1, 4) (139, 1, 0)
(58, 1, 4) (139, 2, 4)
(58, 1, 4) (143, 1, 4)
(58, 1, 4) (144, 2, 5)
(58, 1, 4) (151, 1, 4)
(58, 1, 4) (165, 0, 0)
(58, 1, 4) (172, 0, 4)
(58, 1, 4) (189, 1, 8)
(66, 0, 1) (104, 1, 5)
(66, 0, 1) (136, 0, 4)
(66, 0, 1) (139, 0, 3)
(66, 0, 1) (139, 1, 0)
(66, 0, 1) (139, 2, 4)
(66, 0, 1) (143, 1, 4)
(66, 0, 1) (144, 2, 5)
(66, 0, 1) (151, 1, 4)
(66, 0, 1) (165, 0, 0)
(66, 0, 1) (172, 0, 4)
(66, 0, 1) (189, 1, 8)
(104, 1, 5) (136, 0, 4)
(104, 1, 5) (139, 0, 3)
(104, 1, 5) (139, 1, 0)
(104, 1, 5) (139, 2, 4)
(104, 1, 5) (143, 1, 4)
(104, 1, 5) (144, 2, 5)
(104, 1, 5) (151, 1, 4)
(104, 1